[template]
cargo_generate_version = ">=0.17.4"

[placeholders]
extension_description = { type = "string", prompt = "Extension description" }
extension_author = { type = "string", prompt = "Extension author" }
extension_repository = { type = "string", prompt = "Extension repository URL" }
include_grammar = { type = "bool", prompt = "Do you want to add a new grammar?" }
include_lsp = { type = "bool", prompt = "Do you want to add a new LSP?" }
include_theme = { type = "bool", prompt = "Do you want to add a new theme?" }

[conditional.'include_grammar'.placeholders]
language_name = { prompt = "Language name (e.g., 'python', 'rust', 'javascript')", type = "string" }
grammar_repository = { prompt = "Grammar repository URL", type = "string" }
grammar_commit = { prompt = "Grammar commit hash", type = "string" }

[conditional.'include_theme'.placeholders]
theme_name = { prompt = "Theme name", type = "string" }

[conditional.'include_lsp'.placeholders]
lsp_name = { prompt = "Language server name", type = "string" }

[conditional.'!include_lsp']
ignore = ["Cargo.toml", "src/", ".github/"]

[conditional.'!include_grammar']
ignore = ["languages/"]

[conditional.'!include_theme']
ignore = ["themes/"]
